device:
  cuda_device: 2
  num_workers: 4

training:
  seg_labels: [1]
  loss_type: "Dice_Xent"
  batch_size_train: 10
  batch_size_valid: 1
  nr_train_epochs: 20
  validation_every_n_epochs: 5
  sliding_window_validation: True
  optimiser_choice: "Adam"
  opt_momentum: null
  gradient_clipping: null
  lr: 1e-3
  lr_decay: null
  manual_seed: 0

data:
  data_root: ["/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset/GroupA",
              "/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset/GroupB1",
              "/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset/GroupB2",
              "/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset_extension/GroupC",
              "/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset_extension/GroupD",
              "/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset_extension/GroupE",
              "/mnt/data/mranzini/Desktop/GIFT-Surg/Data/NeuroImage_dataset_extension/GroupF"]
  training_list: "/mnt/data/mranzini/Desktop/GIFT-Surg/Retraining_with_expanded_dataset/config/file_names/list_train_files.txt"
  validation_list: ["/mnt/data/mranzini/Desktop/GIFT-Surg/Retraining_with_expanded_dataset/config/file_names/list_validation_h_files.txt",
                    "/mnt/data/mranzini/Desktop/GIFT-Surg/Retraining_with_expanded_dataset/config/file_names/list_validation_p_files.txt"]

output:
  out_model_dir: "/mnt/data/mranzini/Desktop/GIFT-Surg/FBS_Monai/basic_unet_monai/tests_deterministic_seeds"
  output_subfix: "refactor_monai-0.2.0_recomputecache"
  cache_dir: "/mnt/data/mranzini/Desktop/GIFT-Surg/FBS_Monai/basic_unet_monai/tests_deterministic_seeds/persistent_cache_3Dval_monai0.2.0"
  max_nr_models_saved: 1
  val_image_to_tensorboad: False

log:
  message: "Test code refactoring with SupervisedEvaluator and SupervisedTrainer - training 2D Unet"
